function fail() {
    try {
        //run some code
    } catch (error) {
        //if errors handle them here
        console.log(error)
    }
}

// runs with synchronous code